CREATE DATABASE a_verem_hu
CREATE TABLE `users` (`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY, `name` VARCHAR(12) NOT NULL UNIQUE, `email` VARCHAR(63) NOT NULL UNIQUE, `password_hash` VARCHAR(255) NOT NULL) ENGINE = InnoDB;
CREATE TABLE `temporary_password` (`user_id` INT NOT NULL PRIMARY KEY, `password_hash` VARCHAR(255) NOT NULL, `password_time` DATETIME NOT NULL) ENGINE = InnoDB;
CREATE TABLE `posts` (`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY, `user_id` INT NOT NULL, `reply_id` INT NOT NULL, `post` TEXT NOT NULL, `time` DATETIME NOT NULL, `edit_time` DATETIME NOT NULL) ENGINE = InnoDB;
